In [1]:
import pandas as pd
import numpy as np
import json
import math

In [2]:
#Directories of the TCGA data
CLIN_PATH = '../data/clinical.project-TCGA-BRCA.2016-09-30T12_32_20.666404.json' #Patient data
DIST_PATH = '../data/dd5_5_for_TCGA.txt' # Distance metric
GENOME_PATH = '../data/BRCA.rnaseqv2__illuminahiseq_rnaseqv2__unc_edu__Level_3__RSEM_genes_normalized__data.data.txt' #Genome data

## Reading data files

#### Clinical data of patients

In [3]:
# Clinical data of patients
big_df = pd.read_json(CLIN_PATH)

# Change lists to dictionaries to easily expand to columns in DataFrame
def dictify(df):
    df['diagnoses'] = df['diagnoses'][0]
    df['exposures'] = df['exposures'][0]
    return df

big_df = big_df.dropna().apply(dictify,axis=1)

In [4]:
# Expand dictionaries to columns in DataFrame
df_clin = pd.DataFrame(big_df['case_id']).join(big_df['demographic'].apply(pd.Series),how='outer',lsuffix='_case_id',rsuffix='_demo')\
            .join(big_df['diagnoses'].apply(pd.Series),how='outer',lsuffix = '_demo',rsuffix='_diag')\
            .join(big_df['exposures'].apply(pd.Series),how='outer',lsuffix = '_diag',rsuffix='_expo')

In [5]:
# Drop nulls rows and columns
df_clin.dropna(how='all', inplace = True)
df_clin.dropna(how='all', inplace = True, axis=1)

In [6]:
df_clin.head()

,case_id,demographic_id,ethnicity,gender,race,submitter_id_demo,updated_datetime_demo,year_of_birth,year_of_death,age_at_diagnosis,...,site_of_resection_or_biopsy,submitter_id_diag,tissue_or_organ_of_origin,tumor_grade,tumor_stage,updated_datetime_diag,vital_status,exposure_id,submitter_id,updated_datetime
0,b205c89f-af62-4186-acad-ed23d243fa98,55ae5a3b-e509-5fcd-98c9-c5007b448890,not hispanic or latino,female,white,TCGA-A2-A0YL_demographic,2016-09-02T19:00:43.039678-05:00,1962.0,NaN,17702.0,...,c50.9,TCGA-A2-A0YL_diagnosis,c50.9,not reported,stage iiia,2016-09-02T19:00:43.039678-05:00,alive,23b6a296-e149-5801-aa20-e144ef683abe,TCGA-A2-A0YL_exposure,2016-09-02T19:00:43.039678-05:00
1,70f34c5c-3671-44c8-9469-99f9786efec1,498e27fb-2201-524a-bdd1-86f4e53dc54b,not hispanic or latino,female,white,TCGA-D8-A1XR_demographic,2016-09-02T19:07:03.114741-05:00,1954.0,NaN,20488.0,...,c50.9,TCGA-D8-A1XR_diagnosis,c50.9,not reported,stage iib,2016-09-02T19:07:03.114741-05:00,alive,6dfa11dc-4266-57c9-b746-02a6c7bb9d23,TCGA-D8-A1XR_exposure,2016-09-02T19:07:03.114741-05:00
2,8986a141-eae7-4157-b695-02cc6fc3b071,8faa57d4-1199-53ce-a0ce-24d358841153,not hispanic or latino,female,white,TCGA-BH-A1ET_demographic,2016-09-02T18:57:52.265307-05:00,1944.0,2005.0,20425.0,...,c50.9,TCGA-BH-A1ET_diagnosis,c50.9,not reported,stage i,2016-09-02T18:57:52.265307-05:00,dead,e72e6b02-58be-539a-af7f-f2714f14899a,TCGA-BH-A1ET_exposure,2016-09-02T18:57:52.265307-05:00
3,7317e605-93ba-49a9-8743-20613b02767a,4394b44c-b51d-5b96-b62b-db7f49007b43,not hispanic or latino,female,white,TCGA-E2-A1LE_demographic,2016-09-02T19:09:17.163541-05:00,1937.0,2010.0,26239.0,...,c50.9,TCGA-E2-A1LE_diagnosis,c50.9,not reported,stage iiic,2016-09-02T19:09:17.163541-05:00,dead,4c456a08-ffda-507f-a3e3-d273e5c49864,TCGA-E2-A1LE_exposure,2016-09-02T19:09:17.163541-05:00
4,7e1673f8-5758-4963-8804-d5e39f06205b,eebe9198-74c8-5996-bf88-c56d5fd6832f,not hispanic or latino,female,asian,TCGA-C8-A12V_demographic,2016-09-02T19:02:30.147198-05:00,1955.0,NaN,20346.0,...,c50.9,TCGA-C8-A12V_diagnosis,c50.9,not reported,stage iia,2016-09-02T19:02:30.147198-05:00,alive,dd5fbf53-64a4-5bc0-8ca7-ae05abbcbbac,TCGA-C8-A12V_exposure,2016-09-02T19:02:30.147198-05:00

#### Distances matrix

In [7]:
#Creating DataFrame from the distance-correlation matrix data
df_distances = pd.read_csv(DIST_PATH,sep="\t")

In [8]:
df_distances.head()

,TCGA.3C.AAAU.0.Dis,TCGA.3C.AALI.0.Dis,TCGA.3C.AALJ.0.Dis,TCGA.3C.AALK.0.Dis,TCGA.4H.AAAK.0.Dis,TCGA.5L.AAT0.0.Dis,TCGA.5L.AAT1.0.Dis,TCGA.5T.A9QA.0.Dis,TCGA.A1.A0SB.0.Dis,TCGA.A1.A0SD.0.Dis,...,TCGA.UL.AAZ6.0.Dis,TCGA.UU.A93S.0.Dis,TCGA.V7.A7HQ.0.Dis,TCGA.W8.A86G.0.Dis,TCGA.WT.AB41.0.Dis,TCGA.WT.AB44.0.Dis,TCGA.XX.A899.0.Dis,TCGA.XX.A89A.0.Dis,TCGA.Z7.A8R5.0.Dis,TCGA.Z7.A8R6.0.Dis
TCGA.3C.AAAU.0.Dis,0.000000,0.120880,0.105801,0.109540,0.118014,0.116020,0.138326,0.139012,0.164870,0.109789,...,0.130849,0.177643,0.202318,0.118387,0.204810,0.172970,0.131472,0.147361,0.160945,0.102312
TCGA.3C.AALI.0.Dis,0.120880,0.000000,0.086734,0.086734,0.105240,0.102997,0.095894,0.142688,0.183251,0.114400,...,0.117577,0.143124,0.172721,0.125615,0.158141,0.134712,0.116518,0.119447,0.129105,0.101502
TCGA.3C.AALJ.0.Dis,0.105801,0.086734,0.000000,0.072653,0.091719,0.082123,0.096455,0.141006,0.181756,0.102686,...,0.108979,0.147735,0.151162,0.113216,0.138139,0.120631,0.100941,0.103558,0.112343,0.083557
TCGA.3C.AALK.0.Dis,0.109540,0.086734,0.072653,0.000000,0.040750,0.040376,0.062932,0.144121,0.129292,0.053960,...,0.117827,0.158452,0.146738,0.062870,0.165742,0.102312,0.060814,0.073400,0.080130,0.070721
TCGA.4H.AAAK.0.Dis,0.118014,0.105240,0.091719,0.040750,0.000000,0.037074,0.065612,0.152471,0.113901,0.054209,...,0.143560,0.180884,0.172347,0.065300,0.187800,0.112343,0.059381,0.069163,0.097015,0.078198

#### Genome data

In [9]:
#Creating DataFrame from the Genome data
#Note please change the first two words of the text file: "Hybridization REF" to "Hybridization_REF"
with open(GENOME_PATH) as f:
    row = [row.split()[0:] for row in f]
df_genome = pd.DataFrame(row[1:],columns=row[0])

In [10]:
df_genome.head(n=3)
#Row 0 as it has no information.

,Hybridization_REF,TCGA-3C-AAAU-01A-11R-A41B-07,TCGA-3C-AALI-01A-11R-A41B-07,TCGA-3C-AALJ-01A-31R-A41B-07,TCGA-3C-AALK-01A-11R-A41B-07,TCGA-4H-AAAK-01A-12R-A41B-07,TCGA-5L-AAT0-01A-12R-A41B-07,TCGA-5L-AAT1-01A-12R-A41B-07,TCGA-5T-A9QA-01A-11R-A41B-07,TCGA-A1-A0SB-01A-11R-A144-07,...,TCGA-UL-AAZ6-01A-11R-A41B-07,TCGA-UU-A93S-01A-21R-A41B-07,TCGA-V7-A7HQ-01A-11R-A33J-07,TCGA-W8-A86G-01A-21R-A36F-07,TCGA-WT-AB41-01A-11R-A41B-07,TCGA-WT-AB44-01A-11R-A41B-07,TCGA-XX-A899-01A-11R-A36F-07,TCGA-XX-A89A-01A-11R-A36F-07,TCGA-Z7-A8R5-01A-42R-A41B-07,TCGA-Z7-A8R6-01A-11R-A41B-07
0,gene_id,normalized_count,normalized_count,normalized_count,normalized_count,normalized_count,normalized_count,normalized_count,normalized_count,normalized_count,...,normalized_count,normalized_count,normalized_count,normalized_count,normalized_count,normalized_count,normalized_count,normalized_count,normalized_count,normalized_count
1,?|100130426,0.0000,0.0000,0.9066,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
2,?|100133144,16.3644,9.2659,11.6228,12.0894,6.8468,3.9889,0.0000,1.4644,15.3396,...,0.3992,4.3126,0.0000,5.5624,0.0000,0.0000,14.3858,22.3240,2.2638,6.8865

## Cleaning Data

#### Removing data of the patients that are not in the three datasets

In [11]:
#We know that the label "TCGA-XX-XXXX" is a reference for each patient
#We take as a reference the file with less patients, that is to say: distances matrix data

#Taking df_distances as reference to match the other datasets 
ref_distance = [val.replace(".","-")[0:12] for val in df_distances.columns.tolist()]
print("Number of references: " + str(len(ref_distance)))

Number of references: 1093

In [12]:
#Getting the references for clinical data
ref_clinical = [val[0:12] for val in df_clin['submitter_id_demo'].astype(str).tolist()]
print("Number of references: " + str(len(ref_clinical)))

#Getting the references that are not in the matrix data (References that need to be removed)
ref_clinical_to_remove=list(set(ref_clinical)-set(ref_distance))
print(set(ref_clinical)-set(ref_distance))

Number of references: 1097
{'TCGA-AC-A5EI', 'TCGA-C8-A9FZ', 'TCGA-AR-A0U1', 'TCGA-A7-A0DC'}

In [13]:
#Getting the references for genome data
ref_genome = [val[0:12]for val in df_genome.columns.tolist()[1:]]
print("Number of references: " + str(len(ref_genome)))

Number of references: 1212

In [14]:
#References containing only primary solid tumor TP (01)
ref_genome_tumor=[val for val in df_genome.columns.tolist()[1:] if val[13:15]=="01"]
len(ref_genome_tumor)

1093

In [15]:
#References containing only metastatic TM (06)
ref_genome_tumor_06=[val for val in df_genome.columns.tolist()[1:] if val[13:15]=="06"]
print(len(ref_genome_tumor_06))

7

In [16]:
#References containing solid tissue normal NT (11) -
ref_genome_no_tumor=[val for val in df_genome.columns.tolist()[1:] if val[13:15]=="11"]
print(len(ref_genome_no_tumor))

112

#### Creating new genome DataFrame

In [17]:
#Since we are only going to focus on the primary solid tumor (01), we can get rid of the other references with 11 and 06
df_genome_new=df_genome[["Hybridization_REF"]+[val for val in df_genome.columns.tolist()[1:] if val[13:15]=="01"]].iloc[1:].copy()

In [18]:
df_genome_new.reset_index(drop=True,inplace=True)

In [19]:
#Splitting the Hybridization_REF in order to have gene_id and gene_id_reference
list_gene = [val.split("|")[0] for val in df_genome_new["Hybridization_REF"].tolist()]
list_gene_id = [val.split("|")[1] for val in df_genome_new["Hybridization_REF"].tolist()]
df_genome_new["gene"] = list_gene
df_genome_new["gene_id"] = list_gene_id

In [20]:
cols = df_genome_new.columns.tolist()
df_genome_new = df_genome_new[[cols[-2]]+[cols[-1]]+cols[:-2]]
del df_genome_new["Hybridization_REF"]

In [21]:
df_genome_new.head()

,gene,gene_id,TCGA-3C-AAAU-01A-11R-A41B-07,TCGA-3C-AALI-01A-11R-A41B-07,TCGA-3C-AALJ-01A-31R-A41B-07,TCGA-3C-AALK-01A-11R-A41B-07,TCGA-4H-AAAK-01A-12R-A41B-07,TCGA-5L-AAT0-01A-12R-A41B-07,TCGA-5L-AAT1-01A-12R-A41B-07,TCGA-5T-A9QA-01A-11R-A41B-07,...,TCGA-UL-AAZ6-01A-11R-A41B-07,TCGA-UU-A93S-01A-21R-A41B-07,TCGA-V7-A7HQ-01A-11R-A33J-07,TCGA-W8-A86G-01A-21R-A36F-07,TCGA-WT-AB41-01A-11R-A41B-07,TCGA-WT-AB44-01A-11R-A41B-07,TCGA-XX-A899-01A-11R-A36F-07,TCGA-XX-A89A-01A-11R-A36F-07,TCGA-Z7-A8R5-01A-42R-A41B-07,TCGA-Z7-A8R6-01A-11R-A41B-07
0,?,100130426,0.0000,0.0000,0.9066,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
1,?,100133144,16.3644,9.2659,11.6228,12.0894,6.8468,3.9889,0.0000,1.4644,...,0.3992,4.3126,0.0000,5.5624,0.0000,0.0000,14.3858,22.3240,2.2638,6.8865
2,?,100134869,12.9316,17.3790,9.2294,11.0799,14.4298,13.6090,10.5949,8.9958,...,14.3720,10.8828,3.0792,14.3711,6.3091,3.2580,21.4409,27.2744,7.2933,24.7795
3,?,10357,52.1503,69.7553,154.2974,143.8643,84.2128,114.2572,115.9984,107.5628,...,135.6241,136.1288,29.9974,128.3151,53.6278,42.2643,137.7756,64.1427,85.0461,167.5511
4,?,10431,408.0760,563.8934,1360.8341,865.5358,766.3830,807.7431,1108.3945,1420.5021,...,1570.1445,2886.3965,1721.8816,697.6744,1245.2681,1877.4180,652.7559,722.7208,1140.2801,1003.5668

In [ ]:
df_genome_new.to_csv("genome_data.csv",sep=",",index=False)

#### Creating new clinical DataFrame

In [52]:
#Adding a new column with the references only (TCGA-XXXX-XX format)
df_clin["reference"]= [val[0:12] for val in df_clin["submitter_id_demo"].astype(str).tolist()]

In [53]:
#Creating new clinical dataframe
to_remove=["case_id","demographic_id","submitter_id_demo","updated_datetime_demo",
          "classification_of_tumor","days_to_last_follow_up","diagnosis_id","last_known_disease_status",
          "prior_malignancy","progression_or_recurrence","tumor_grade","exposure_id","submitter_id",
          "updated_datetime_diag", "updated_datetime","submitter_id_diag","primary_diagnosis",
           "site_of_resection_or_biopsy","days_to_birth","year_of_death"]
df_clin_new=df_clin.drop(to_remove,axis=1)

In [54]:
df_clin_new=df_clin_new[df_clin_new["reference"].isin([val[0:12] for val in df_genome.columns.tolist()[1:] if val[13:15]=="01"])]
df_clin_new.reset_index(drop=True,inplace=True)

In [55]:
#Fixing year of birth
df_clin_new["year_of_birth"]=[int(x) if not math.isnan(x) else x for x in df_clin_new.year_of_birth.tolist()]

In [56]:
#Fixing age_at_diagnosis
df_clin_new["age_at_diagnosis"]=df_clin_new.age_at_diagnosis.apply(lambda x: round(float(x)/365,0) if not math.isnan(float(x)) else None)
df_clin_new["age_at_diagnosis"]=[int(x) if not math.isnan(x) else x for x in df_clin_new.age_at_diagnosis.tolist()]

In [57]:
#Fixing days_to_death
df_clin_new["days_to_death"]=df_clin_new.days_to_death.apply(lambda x: round(x/365,0) if not math.isnan(x) else None)
df_clin_new["days_to_death"]=[int(x) if not math.isnan(x) else x for x in df_clin_new.days_to_death.tolist()]
df_clin_new.rename(columns={"days_to_death":"years_to_death"},inplace=True)

In [58]:
#Mapping the morphology code to its name
dict_morphology={"8520/3":"Lobular Carcinoma", #Second most common
                 "8500/3":"Infiltrating Duct Carcinoma", #Most common
                "8575/3":"Metaplastic Carcinoma",#Only in 1% of all breast cancer
                "8523/3":"Infiltrating Duct Mixed with Other Types Of Carcinoma",
                "8211/3":"Tubular Adenocarcinoma",
                "8522/3":"Infiltrating Duct and Lobular Carcinoma",
                "9020/3":"Phyllodes Tumor",
                "8541/3":"Paget Disease and Infiltrating Duct Carcinoma of Breast",
                "8480/3":"Mucinous Adenocarcinoma",
                "8503/3":"Intraductal Papillary Adenocarcinoma with Invasion",
                "8090/3":"Basal Cell Carcinoma",
                "8502/3":"Secretory Carcinoma of Breast",
                "8510/3":"Medullary Carcinoma",
                "8524/3":"Infiltrating Lobular Mixed with Other Types of Carcinoma",
                "8010/3":"Carcinoma",
                "8507/3":"Infiltrating Ductal",
                "8022/3":"Pleomorphic Carcinoma",
                "8050/3":"Papillary Carcinoma",
                "8201/3":"Cribriform Carcinoma",
                "8013/3":"Large Cell Neuroendocrine Carcinoma",
                "8200/3":"Adenoid Cystic Carcinoma",
                "8401/3":"Apocrine Adenocarcinoma"} 
df_clin_new["morphology_code"]=df_clin_new["morphology"].tolist()
df_clin_new.replace({"morphology":dict_morphology},inplace=True)

In [59]:
#Mapping the tissue or organ of origin
dict_tissue={"c50.9":"Malignant neoplasm of breast of unspecified site",
            "c50.8":"Malignant neoplasm of overlapping sites of breast",
            "c50.3":"Malignant neoplasm of lower-inner quadrant of breast",
            "c50.4":"Malignant neoplasm of upper-outer quadrant of breast",
            "c50.2":"Malignant neoplasm of upper-inner quadrant of breast",
            "c50.5":"Malignant neoplasm of lower-outer quadrant of breast"}
df_clin_new["tissue_of_origin_code"]=df_clin_new["tissue_or_organ_of_origin"].tolist()
df_clin_new.replace({"tissue_or_organ_of_origin":dict_tissue},inplace=True)

In [60]:
#Not considering normal tissue: Getting the center code
list_ref=[val for val in df_genome.columns.tolist()[1:] if (val[13:15]=="01")]

In [61]:
#Characterization_center
dict_center={"07":"University of North Carolina"}
dict_center_code={}
for patient in list_ref:
    dict_center_code[patient[0:12]]=patient[26:28]
df_clin_new["characterization_center_code"]=df_clin_new["reference"].tolist()
df_clin_new.replace({"characterization_center_code":dict_center_code},inplace=True)
df_clin_new["characterization_center"]=df_clin_new["characterization_center_code"].tolist()
df_clin_new.replace({"characterization_center":dict_center},inplace=True)

In [62]:
#Getting the tissue code
dict_tissue_code={}
for patient in list_ref:
    dict_tissue_code[patient[0:12]]=patient[5:7]
df_clin_new["tissue_source_code"]=df_clin_new["reference"].tolist()
df_clin_new.replace({"tissue_source_code":dict_tissue_code},inplace=True)

In [63]:
#Creating the dictionary for the tissue code and its values (Institute, Study name, Country and state)
dict_tissue_source={"A2":["Walter Reed Army Medical Center","Breast invasive carcinoma","USA","Washington D.C."],
                         "D8":["Greater Poland Cancer Center","Breast invasive carcinoma","Poland","Greater Poland"],
                         "BH":["University of Pittsburgh","Breast invasive carcinoma","USA","Pennsylvania"],
                         "E2":["Roswell Park Cancer Institute","Breast invasive carcinoma","USA","New York"],
                         "C8":["ILSBio","Breast invasive carcinoma","USA","Maryland"],
                         "AQ":["University of North Carolina","Breast invasive carcinoma","USA","North Carolina"],
                         "AN":["Cureline","Breast invasive carcinoma","USA","California"],
                         "V7":["Medical College of Georgia","Breast invasive carcinoma","USA","Georgia"],
                         "S3":["Albert Einstein Medical Center","Breast invasive carcinoma","USA","Pennsylvania"],
                         "A8":["Indivumed","Breast invasive carcinoma","Germany","Hamburg"],
                         "GM":["MD Anderson Cancer Center","Breast invasive carcinoma","USA","Texas"],
                         "AR":["Mayo Clinic","Breast invasive carcinoma","USA","Minnesota"],
                         "E9":["Asterand Bioscience","Breast invasive carcinoma","USA","Michigan"],
                         "A7":["Christiana Care Health System","Breast invasive carcinoma","USA","Delaware"],
                         "AO":["Memorial Sloan Kettering Cancer Center","Breast invasive carcinoma","USA","NY"],
                         "B6":["Duke Cancer Institute","Breast invasive carcinoma","USA","North Carolina"],
                         "AC":["International Genomics Consortium","Breast invasive carcinoma","USA","Arizona"],
                         "PE":["Fox Chase Cancer Center","Breast invasive carcinoma","USA","Pennsylvania"],
                         "EW":["University of Miami","Breast invasive carcinoma","USA","Florida"],
                         "XX":["Spectrum Health","Breast invasive carcinoma","USA","Michigan"],
                         "OL":["University of Chicago","Breast invasive carcinoma","USA","Illinois"],
                         "GI":["Indiana Universityâ€“Purdue University Indianapolis","Breast invasive carcinoma","USA","Indiana"],
                         "3C":["Columbia University","Breast invasive carcinoma","USA","New York"],
                         "LL":["Candler Hospital","Breast invasive carcinoma","USA","Georgia"],
                         "OK":["Mount Sinai School of Medicine","Breast invasive carcinoma","USA","New York"],
                         "WT":["University of Kansas","Breast invasive carcinoma","USA","Kansas"],
                         "JL":["Metrics Research Pakistan","Breast invasive carcinoma","Pakistan","Sindh"],
                         "LD":["Hartford Hospital","Breast invasive carcinoma","USA","Connecticut"],
                         "UL":["Boston Medical Center","Breast invasive carcinoma","USA","California"],
                         "A1":["University of California San Francisco","Breast invasive carcinoma","USA","California"],
                         "PL":["Institute of Human Virology Nigeria","Breast invasive carcinoma","Nigeria","Federal Capital Territory"],
                         "HN":["Ontario Institute for Cancer Research","Breast invasive carcinoma","Canada","Ontario"],
                         "5L":["University of Sao Paulo","Breast invasive carcinoma","Brazil","Sao Paulo"],
                         "Z7":["John Wayne Cancer Institute","Breast invasive carcinoma","USA","California"],
                         "5T":["Holy Cross Health Center","Breast invasive carcinoma","USA","Maryland"],
                         "UU":["Mary Bird Perkins Cancer Center - Our Lady of the Lake","Breast invasive carcinoma","USA","Louisiana"],
                         "LQ":["Gundersen Lutheran Health System","Breast invasive carcinoma","USA","Wisconsin"],
                         "4H":["Proteogenex Inc","Breast invasive carcinoma","USA","California"],
                         "MS":["University of Minnesota","Breast invasive carcinoma","USA","Minnesota"],
                         "W8":["Greenville Health System","Breast invasive carcinoma","USA","South Carolina"]
                        }
dict_tissue_source_institute={}
dict_tissue_source_study_name={}
dict_tissue_source_country={}
dict_tissue_source_state={}
for code in dict_tissue_source:
    dict_tissue_source_institute[code]=dict_tissue_source[code][0]
    dict_tissue_source_study_name[code]=dict_tissue_source[code][1]
    dict_tissue_source_country[code]=dict_tissue_source[code][2]
    dict_tissue_source_state[code]=dict_tissue_source[code][3]

In [64]:
#Mapping tissue codes to its values
df_clin_new["tissue_source_institute"]=df_clin_new["tissue_source_code"].tolist()
df_clin_new["tissue_source_study_name"]=df_clin_new["tissue_source_code"].tolist()
df_clin_new["tissue_source_country"]=df_clin_new["tissue_source_code"].tolist()
df_clin_new["tissue_source_state"]=df_clin_new["tissue_source_code"].tolist()
df_clin_new.replace({"tissue_source_institute":dict_tissue_source_institute},inplace=True)
df_clin_new.replace({"tissue_source_study_name":dict_tissue_source_study_name},inplace=True)
df_clin_new.replace({"tissue_source_country":dict_tissue_source_country},inplace=True)
df_clin_new.replace({"tissue_source_state":dict_tissue_source_state},inplace=True)

In [65]:
#Rearranging the columns
ordered_cols=["reference","gender","ethnicity","race","vital_status","year_of_birth","age_at_diagnosis",
              "years_to_death","tissue_of_origin_code","tissue_or_organ_of_origin","morphology_code","morphology",
              "tumor_stage","tissue_source_code","tissue_source_institute","tissue_source_study_name",
              "tissue_source_country","tissue_source_state","characterization_center_code","characterization_center"]

In [66]:
df_clin_new=df_clin_new[ordered_cols]

In [67]:
#Cleaning races names
#Replacing latino in the race cells that are marked as not-reported and which ethnicity is latino.
for n,race in enumerate(df_clin_new.race.tolist()):
    if df_clin_new.race[n]=="not reported" and df_clin_new.ethnicity[n]=="hispanic or latino":
        df_clin_new.at[n,"race"]="latino"
dict_races={"black or african american":"black","american indian or alaska native":"native american"}
df_clin_new.replace({"race":dict_races},inplace=True)

#Dropping ethnicity column
df_clin_new.drop(["ethnicity"],axis=1,inplace=True)

In [68]:
df_clin_new.head()

,reference,gender,race,vital_status,year_of_birth,age_at_diagnosis,years_to_death,tissue_of_origin_code,tissue_or_organ_of_origin,morphology_code,morphology,tumor_stage,tissue_source_code,tissue_source_institute,tissue_source_study_name,tissue_source_country,tissue_source_state,characterization_center_code,characterization_center
0,TCGA-A2-A0YL,female,white,alive,1962.0,48.0,NaN,c50.9,Malignant neoplasm of breast of unspecified site,8520/3,Lobular Carcinoma,stage iiia,A2,Walter Reed Army Medical Center,Breast invasive carcinoma,USA,Washington D.C.,07,University of North Carolina
1,TCGA-D8-A1XR,female,white,alive,1954.0,56.0,NaN,c50.9,Malignant neoplasm of breast of unspecified site,8500/3,Infiltrating Duct Carcinoma,stage iib,D8,Greater Poland Cancer Center,Breast invasive carcinoma,Poland,Greater Poland,07,University of North Carolina
2,TCGA-BH-A1ET,female,white,dead,1944.0,56.0,7.0,c50.9,Malignant neoplasm of breast of unspecified site,8500/3,Infiltrating Duct Carcinoma,stage i,BH,University of Pittsburgh,Breast invasive carcinoma,USA,Pennsylvania,07,University of North Carolina
3,TCGA-E2-A1LE,female,white,dead,1937.0,72.0,2.0,c50.9,Malignant neoplasm of breast of unspecified site,8500/3,Infiltrating Duct Carcinoma,stage iiic,E2,Roswell Park Cancer Institute,Breast invasive carcinoma,USA,New York,07,University of North Carolina
4,TCGA-C8-A12V,female,asian,alive,1955.0,56.0,NaN,c50.9,Malignant neoplasm of breast of unspecified site,8500/3,Infiltrating Duct Carcinoma,stage iia,C8,ILSBio,Breast invasive carcinoma,USA,Maryland,07,University of North Carolina

In [69]:
#Since those are too many headers to display, we will only focus on the following: 
#references, gender, race, age at diagnosis and tissue source country
df_clin_viz=df_clin_new[["reference","gender","race","age_at_diagnosis","tissue_source_country"]].copy()

In [96]:
groups=[]
for row in df_clin_viz["age_at_diagnosis"]:
    if row<50:
        groups.append("less_than_50")
    if row>=50 and row <60:
        groups.append("between_50_and_60")
    if row>=60 and row <70:
        groups.append("between_60_and_70")
    if row>=70:
        groups.append("more_than_70")
    if math.isnan(row):
        groups.append("not_reported")

In [100]:
df_clin_viz["age_groups"]=groups
df_clin_viz.drop(["age_at_diagnosis"],axis=1,inplace=True)

In [102]:
df_clin_viz.head()

      reference  gender   race tissue_source_country         age_groups
0  TCGA-A2-A0YL  female  white                   USA       less_than_50
1  TCGA-D8-A1XR  female  white                Poland  between_50_and_60
2  TCGA-BH-A1ET  female  white                   USA  between_50_and_60
3  TCGA-E2-A1LE  female  white                   USA       more_than_70
4  TCGA-C8-A12V  female  asian                   USA  between_50_and_60

In [136]:
df_clin_viz.groupby(["gender","race","tissue_source_country","age_groups"]).count()

                                                                reference
gender race            tissue_source_country age_groups
female asian           Pakistan              not_reported               2
                       USA                   between_50_and_60         19
                                             between_60_and_70          9
                                             less_than_50              14
                                             more_than_70               6
                                             not_reported              11
       black           Nigeria               between_50_and_60          1
                                             less_than_50               3
                       USA                   between_50_and_60         48
                                             between_60_and_70         36
                                             less_than_50              53
                                             more_than_70              37
                                             not_reported               2
       latino          USA                   less_than_50               1
                                             more_than_70               1
       native american USA                   between_50_and_60          1
       not reported    Canada                between_50_and_60          1
                                             less_than_50               1
                       Germany               between_50_and_60         14
                                             between_60_and_70         26
                                             less_than_50               9
                                             more_than_70              34
                       USA                   between_50_and_60          1
                                             between_60_and_70          4
                                             less_than_50               2
       white           Brazil                between_60_and_70          1
                                             less_than_50               1
                       Poland                between_50_and_60         22
                                             between_60_and_70         18
                                             less_than_50              13
                                             more_than_70              24
                       USA                   between_50_and_60        164
                                             between_60_and_70        193
                                             less_than_50             177
                                             more_than_70             131
                                             not_reported               1
male   black           USA                   between_50_and_60          3
       not reported    Germany               less_than_50               1
       white           Poland                less_than_50               1
                       USA                   between_50_and_60          1
                                             between_60_and_70          3
                                             more_than_70               3

In [ ]:
df_clin_viz.to_csv("clinical_data.csv",sep=",",index=False)

## New distances matrix DataFrame

In [40]:
df_distances_new = df_distances.copy()

In [41]:
columns_dict = {}
for n,key in enumerate(df_distances.columns.tolist()):
    columns_dict[key] = [val.replace(".","-")[0:12] for val in df_distances.columns.tolist()][n]

In [42]:
#Just to keep the same format, we rename the distances matrix headers and indices
df_distances_new.rename(columns=columns_dict,index=columns_dict,inplace=True)

In [43]:
df_distances_new.head()

,TCGA-3C-AAAU,TCGA-3C-AALI,TCGA-3C-AALJ,TCGA-3C-AALK,TCGA-4H-AAAK,TCGA-5L-AAT0,TCGA-5L-AAT1,TCGA-5T-A9QA,TCGA-A1-A0SB,TCGA-A1-A0SD,...,TCGA-UL-AAZ6,TCGA-UU-A93S,TCGA-V7-A7HQ,TCGA-W8-A86G,TCGA-WT-AB41,TCGA-WT-AB44,TCGA-XX-A899,TCGA-XX-A89A,TCGA-Z7-A8R5,TCGA-Z7-A8R6
TCGA-3C-AAAU,0.000000,0.120880,0.105801,0.109540,0.118014,0.116020,0.138326,0.139012,0.164870,0.109789,...,0.130849,0.177643,0.202318,0.118387,0.204810,0.172970,0.131472,0.147361,0.160945,0.102312
TCGA-3C-AALI,0.120880,0.000000,0.086734,0.086734,0.105240,0.102997,0.095894,0.142688,0.183251,0.114400,...,0.117577,0.143124,0.172721,0.125615,0.158141,0.134712,0.116518,0.119447,0.129105,0.101502
TCGA-3C-AALJ,0.105801,0.086734,0.000000,0.072653,0.091719,0.082123,0.096455,0.141006,0.181756,0.102686,...,0.108979,0.147735,0.151162,0.113216,0.138139,0.120631,0.100941,0.103558,0.112343,0.083557
TCGA-3C-AALK,0.109540,0.086734,0.072653,0.000000,0.040750,0.040376,0.062932,0.144121,0.129292,0.053960,...,0.117827,0.158452,0.146738,0.062870,0.165742,0.102312,0.060814,0.073400,0.080130,0.070721
TCGA-4H-AAAK,0.118014,0.105240,0.091719,0.040750,0.000000,0.037074,0.065612,0.152471,0.113901,0.054209,...,0.143560,0.180884,0.172347,0.065300,0.187800,0.112343,0.059381,0.069163,0.097015,0.078198

In [ ]:
df_distances_new.to_csv("distances_matrix.csv",sep=",",index=True)